version: "3.4"
volumes:
  database:
    driver: local
  redis:
    driver: local
  gems_volume_log:
    driver: local

services:
  postgres:
      image: postgres:10.5
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - "5438:5432"
      volumes: 
        - database:/var/lib/postgresql/data

  frontend:
    volumes:
      - ./:/app
    command: npm run start
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      REACT_APP_API_ROOT: http://localhost:7107
      PORT: 7108
    ports:
      - 7108:7108

  backend:
    volumes:
      - ../reading-log-api:/app
      - gems_volume_log:/usr/local/bundle
      - /home/danilo/scripts/ruby/leituras.txt:/leituras.txt
    command: ./startup_local.sh
    build:
      context: ../reading-log-api
      dockerfile: Dockerfile
    ports:
      - 7107:7107
    environment:
      RAILS_ENV: development
      RAKE_ENV: development
      DB_DATABASE: development
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASS: postgres
    expose:
      - 7107
